-- Enable the pgvector extension for embeddings
create extension if not exists vector;

-- 1. Users Table (Extends Supabase Auth)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text unique not null,
  full_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Domain Profiles (Maps student to a selected domain)
create table public.domain_profiles (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  domain_name text not null, -- e.g., 'Computer Engineering', 'Artificial Intelligence'
  current_competency_level text check (current_competency_level in ('Beginner', 'Intermediate', 'Advanced')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, domain_name)
);

-- 3. Quiz Results (Stores the real-time assessment data)
create table public.quiz_results (
  id uuid default gen_random_uuid() primary key,
  domain_profile_id uuid references public.domain_profiles(id) on delete cascade not null,
  score numeric not null,
  raw_responses jsonb not null, -- Stores question, user answer, correctness
  taken_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Identified Flaws (Extracted sub-concept gaps based on incorrect quiz responses)
create table public.identified_flaws (
  id uuid default gen_random_uuid() primary key,
  quiz_result_id uuid references public.quiz_results(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null,
  concept_name text not null, -- e.g., 'Pointer Arithmetic', 'Gradient Descent'
  description text not null,
  embedding vector(1536), -- Vector embedding to match against course materials
  is_remediated boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Course Catalog (Available courses/modules)
create table public.courses (
  id uuid default gen_random_uuid() primary key,
  domain_name text not null,
  title text not null,
  description text not null,
  prerequisites text[],
  embedding vector(1536), -- Vector representation of course content for semantic matching
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Course Recommendations (Predictive pathway generated by the system)
create table public.course_recommendations (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  domain_profile_id uuid references public.domain_profiles(id) on delete cascade not null,
  course_id uuid references public.courses(id) on delete cascade not null,
  recommendation_reason text,
  confidence_score numeric,
  order_index integer not null, -- Sequential order of the recommended pathway
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================
-- Row Level Security (RLS) Setup
-- ==========================================

alter table public.profiles enable row level security;
alter table public.domain_profiles enable row level security;
alter table public.quiz_results enable row level security;
alter table public.identified_flaws enable row level security;
alter table public.courses enable row level security;
alter table public.course_recommendations enable row level security;

-- RLS Policies
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

create policy "Users can view own domain profiles" on public.domain_profiles for select using (auth.uid() = user_id);
create policy "Users can insert own domain profiles" on public.domain_profiles for insert with check (auth.uid() = user_id);

create policy "Users can view own quiz results" on public.quiz_results for select using (
  auth.uid() = (select user_id from public.domain_profiles where id = domain_profile_id)
);
create policy "Users can insert own quiz results" on public.quiz_results for insert with check (
  auth.uid() = (select user_id from public.domain_profiles where id = domain_profile_id)
);

create policy "Users can view own flaws" on public.identified_flaws for select using (auth.uid() = user_id);
create policy "Users can update own flaws (mark remediated)" on public.identified_flaws for update using (auth.uid() = user_id);

create policy "Courses are readable by everyone" on public.courses for select using (true);

create policy "Users can view own recommendations" on public.course_recommendations for select using (auth.uid() = user_id);

-- ==========================================
-- Triggers and Functions
-- ==========================================

-- Function to update 'updated_at' timestamp
create or replace function handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger profiles_updated_at
  before update on public.profiles
  for each row execute procedure handle_updated_at();

-- Function to automatically create profile on user signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
